local luagrapheme = require("luagrapheme")

describe("luagrapheme.grapheme_breaks", function()
   it("exists", function()
      assert.is_not_nil(luagrapheme.grapheme_breaks)
   end)

   it("errors when argument #1 is not a string", function()
      assert.has_error(function()
         luagrapheme.grapheme_breaks()
      end, "bad argument #1 to 'grapheme_breaks' (string expected, got no value)")
      assert.has_error(function()
         luagrapheme.grapheme_breaks(nil)
      end, "bad argument #1 to 'grapheme_breaks' (string expected, got nil)")
      assert.has_no_error(function()
         luagrapheme.grapheme_breaks("hello")
      end)
   end)

   it("returns a function", function()
      local next = luagrapheme.grapheme_breaks("hello")
      assert.is_function(next)
   end)

   it("works with an empty string", function()
      local next = luagrapheme.grapheme_breaks("")
      assert.is_nil(next())
   end)

   it("works with ASCII text", function()
      local next = luagrapheme.grapheme_breaks("hello")
      assert.are.equal(1, next())
      assert.are.equal(2, next())
      assert.are.equal(3, next())
      assert.are.equal(4, next())
      assert.are.equal(5, next())
      assert.is_nil(next())
      assert.is_nil(next())
   end)

   it("works with multi-code point grapheme clusters", function()
      local next = luagrapheme.grapheme_breaks("he👩‍🚀llo")
      assert.are.equal(1, next())
      assert.are.equal(2, next())
      assert.are.equal(3, next())
      assert.are.equal(14, next())
      assert.are.equal(15, next())
      assert.are.equal(16, next())
      assert.is_nil(next())
      assert.is_nil(next())
   end)
end)
