local uni = require("uni")

describe("uni.graphemes", function()
   it("exists", function()
      assert.is_not_nil(uni.graphemes)
   end)

   it("errors when the input is not a string", function()
      assert.has_error(function()
         uni.graphemes(nil)
      end, "bad argument #1 to 'graphemes' (string expected, got nil)")
   end)

   it("returns a function", function()
      local next = uni.graphemes("hello")
      assert.is_function(next)
   end)

   it("works with an empty string", function()
      local next = uni.graphemes("")
      assert.is_nil(next())
   end)

   it("works with ASCII text", function()
      local next = uni.graphemes("hello")
      assert.are.equal("h", next())
      assert.are.equal("e", next())
      assert.are.equal("l", next())
      assert.are.equal("l", next())
      assert.are.equal("o", next())
      assert.is_nil(next())
   end)

   it("works with multi-code point grapheme clusters", function()
      local next = uni.graphemes("he👩‍🚀llo")
      assert.are.equal("h", next())
      assert.are.equal("e", next())
      assert.are.equal("👩‍🚀", next())
      assert.are.equal("l", next())
      assert.are.equal("l", next())
      assert.are.equal("o", next())
      assert.is_nil(next())
   end)
end)
