local luagrapheme = require("luagrapheme")

describe("luagrapheme.len", function()
   it("exists", function()
      assert.is_not_nil(luagrapheme.len)
   end)

   it("errors when argument #1 is not a string", function()
      assert.has_error(function()
         luagrapheme.len()
      end, "bad argument #1 to 'len' (string expected, got no value)")
      assert.has_error(function()
         luagrapheme.len(nil)
      end, "bad argument #1 to 'len' (string expected, got nil)")
      assert.has_no_error(function()
         luagrapheme.len("hello")
      end)
   end)

   it("works with an empty string", function()
      assert.are.equal(0, luagrapheme.len(""))
   end)

   it("works with ASCII text", function()
      assert.are.equal(3, luagrapheme.len("Lua"))
   end)

   it("works with multi-code point grapheme clusters", function()
      assert.are.equal(6, luagrapheme.len("he👩‍🚀llo"))
   end)
end)
